"""
Email Module

This module provides Gmail integration functionality including:
- Gmail service client for sending and receiving emails
- Email summarization and analysis
- Modular email features (drafts, attachments, categorization, scheduling, etc.)
"""

from .gmail_service import (
    GmailServiceClient,
    send_email,
    send_email_with_attachment,
    list_emails,
    get_inbox_count,
    get_todays_emails,
    delete_emails,
    summarize_email,
    summarize_thread,
    generate_daily_digest,
    # Feature wrappers
    extract_action_items,
    get_all_pending_actions,
    generate_reply_suggestions,
    quick_reply,
    create_draft,
    list_drafts,
    send_draft,
    delete_draft,
    list_attachments,
    download_attachment,
    search_emails_with_attachments,
    auto_categorize_email,
    apply_smart_labels,
    extract_calendar_events,
    suggest_calendar_entry,
    mark_for_followup,
    get_pending_followups,
    check_unanswered_emails,
    schedule_email,
    list_scheduled_emails,
    cancel_scheduled_email,
    get_frequent_contacts,
    get_contact_summary,
    detect_urgent_emails,
    auto_prioritize,
    detect_newsletters,
    extract_unsubscribe_link,
    get_email_stats,
    get_productivity_insights,
    # Phase 4 additions
    calculate_response_time,
    visualize_patterns,
    generate_weekly_report,
    mark_action_complete,
    get_saved_tasks,
    create_category_rules,
    export_to_calendar,
    send_followup_reminder,
    mark_followup_done,
    dismiss_followup,
    update_scheduled_email,
    suggest_vip_contacts,
    export_contacts,
)

__all__ = [
    'GmailServiceClient',
    'send_email',
    'send_email_with_attachment',
    'list_emails',
    'get_inbox_count',
    'get_todays_emails',
    'delete_emails',
    'summarize_email',
    'summarize_thread',
    'generate_daily_digest',
    # Features
    'extract_action_items',
    'get_all_pending_actions',
    'generate_reply_suggestions',
    'quick_reply',
    'create_draft',
    'list_drafts',
    'send_draft',
    'delete_draft',
    'list_attachments',
    'download_attachment',
    'search_emails_with_attachments',
    'auto_categorize_email',
    'apply_smart_labels',
    'extract_calendar_events',
    'suggest_calendar_entry',
    'mark_for_followup',
    'get_pending_followups',
    'check_unanswered_emails',
    'schedule_email',
    'list_scheduled_emails',
    'cancel_scheduled_email',
    'get_frequent_contacts',
    'get_contact_summary',
    'detect_urgent_emails',
    'auto_prioritize',
    'detect_newsletters',
    'extract_unsubscribe_link',
    'get_email_stats',
    'get_productivity_insights',
    # Phase 4
    'calculate_response_time',
    'visualize_patterns',
    'generate_weekly_report',
    'mark_action_complete',
    'get_saved_tasks',
    'create_category_rules',
    'export_to_calendar',
    'send_followup_reminder',
    'mark_followup_done',
    'dismiss_followup',
    'update_scheduled_email',
    'suggest_vip_contacts',
    'export_contacts',
]
