"""
Stock Analysis Report Generator — PDF via reportlab
=====================================================

Produces a structured, multi-section PDF analysis report.

Inputs  : structured dicts from all stock analysis tools + LLM narrative
Output  : PDF file saved to disk, path returned

Layout:
  Cover page  — name, date, symbol, SEBI/general disclaimer
  Section 1   — Executive Summary (LLM narrative)
  Section 2   — Market Snapshot (current quote)
  Section 3   — Fundamental Analysis (Buffett metrics, moat score)
  Section 4   — Technical Analysis (RSI/MACD/Bollinger/SMA)
  Section 5   — Risk Assessment (volatility/Beta/VaR/Sharpe/MaxDD)
  Section 6   — Chart Pattern Detection
  Section 7   — News Sentiment
  Footer      — disclaimer on every page

NO buy/sell recommendations. NO price targets. Informational only.

Requires: pip install reportlab
"""
from __future__ import annotations

import os
from datetime import datetime
from typing import Any, Dict, List, Optional

# ── Reportlab imports (lazy, with clear error) ─────────────────────────────────

def _rl():
    try:
        import reportlab
        return reportlab
    except ImportError:
        raise ImportError("reportlab is not installed. Run: pip install reportlab")


# ── Colour palette ─────────────────────────────────────────────────────────────

_NAVY   = (0.05, 0.14, 0.33)   # dark header bg
_TEAL   = (0.00, 0.53, 0.60)   # accent / section headers
_LIGHT  = (0.94, 0.96, 0.98)   # alternating table rows
_WHITE  = (1.00, 1.00, 1.00)
_RED    = (0.80, 0.10, 0.10)
_GREEN  = (0.05, 0.55, 0.18)
_ORANGE = (0.85, 0.45, 0.05)
_GRAY   = (0.55, 0.55, 0.55)
_BLACK  = (0.10, 0.10, 0.10)

_DISCLAIMER = (
    "IMPORTANT DISCLAIMER: This report is generated by OctaMind for informational and "
    "educational purposes ONLY. It does NOT constitute financial advice, investment advice, "
    "trading advice, or any other type of advice. No buy, sell, or hold recommendation is "
    "made for any security. Past performance is not indicative of future results. "
    "Investments in securities are subject to market risk. Please read all scheme-related "
    "documents carefully and consult a SEBI-registered investment advisor before making any "
    "investment decision. OctaMind and its operators are NOT registered with SEBI or any "
    "regulatory authority as investment advisors."
)


# ── Helper: build paragraph style ──────────────────────────────────────────────

def _styles():
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
    from reportlab.lib.units import pt
    from reportlab.lib import colors

    base = getSampleStyleSheet()

    def rgb(t):
        return colors.Color(*t)

    styles = {}

    styles["title"] = ParagraphStyle(
        "OmTitle",
        parent=base["Title"],
        fontSize=22,
        textColor=rgb(_WHITE),
        alignment=TA_CENTER,
        spaceAfter=6,
    )
    styles["subtitle"] = ParagraphStyle(
        "OmSubtitle",
        parent=base["Normal"],
        fontSize=12,
        textColor=rgb(_LIGHT),
        alignment=TA_CENTER,
        spaceAfter=4,
    )
    styles["section"] = ParagraphStyle(
        "OmSection",
        parent=base["Heading2"],
        fontSize=12,
        textColor=rgb(_WHITE),
        backColor=rgb(_TEAL),
        leading=16,
        spaceBefore=12,
        spaceAfter=4,
        leftIndent=-6,
        borderPad=4,
    )
    styles["body"] = ParagraphStyle(
        "OmBody",
        parent=base["Normal"],
        fontSize=9,
        textColor=rgb(_BLACK),
        leading=13,
        spaceAfter=4,
    )
    styles["body_small"] = ParagraphStyle(
        "OmBodySmall",
        parent=base["Normal"],
        fontSize=7.5,
        textColor=rgb(_GRAY),
        leading=10,
        spaceAfter=2,
    )
    styles["disc_style"] = ParagraphStyle(
        "OmDisc",
        parent=base["Normal"],
        fontSize=6.5,
        textColor=rgb(_ORANGE),
        leading=9,
    )
    styles["kv_key"] = ParagraphStyle(
        "OmKVKey",
        parent=base["Normal"],
        fontSize=8.5,
        textColor=rgb(_GRAY),
        leading=12,
    )
    styles["kv_val"] = ParagraphStyle(
        "OmKVVal",
        parent=base["Normal"],
        fontSize=8.5,
        textColor=rgb(_BLACK),
        leading=12,
    )
    styles["bold"] = ParagraphStyle(
        "OmBold",
        parent=base["Normal"],
        fontSize=9,
        textColor=rgb(_BLACK),
        leading=13,
        fontName="Helvetica-Bold",
    )
    return styles


# ── Helper: coloured table ─────────────────────────────────────────────────────

def _table(data: List[List[str]], col_widths, header_bg=None):
    """Build a reportlab Table with alternating row shading."""
    from reportlab.platypus import Table, TableStyle
    from reportlab.lib import colors

    def rgb(t):
        return colors.Color(*t)

    hbg = rgb(header_bg or _NAVY)

    style_cmds = [
        ("BACKGROUND",  (0, 0), (-1, 0), hbg),
        ("TEXTCOLOR",   (0, 0), (-1, 0), colors.white),
        ("FONTNAME",    (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",    (0, 0), (-1, 0), 8),
        ("FONTSIZE",    (0, 1), (-1, -1), 8),
        ("FONTNAME",    (0, 1), (-1, -1), "Helvetica"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, rgb(_LIGHT)]),
        ("GRID",        (0, 0), (-1, -1), 0.25, rgb(_GRAY)),
        ("VALIGN",      (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING",  (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ]
    t = Table(data, colWidths=col_widths)
    t.setStyle(TableStyle(style_cmds))
    return t


# ── Helper: score badge ────────────────────────────────────────────────────────

def _score_bar(score: float, max_score: float = 10, label: str = "") -> str:
    filled = int(round(score))
    empty  = int(max_score) - filled
    bar    = "█" * filled + "░" * empty
    return f"{bar}  {score}/{int(max_score)}  {label}"


# ── Null-safe formatting ────────────────────────────────────────────────────────

def _fmt(val: Any, suffix: str = "", decimals: int = 2, na: str = "N/A") -> str:
    if val is None:
        return na
    try:
        return f"{float(val):.{decimals}f}{suffix}"
    except (TypeError, ValueError):
        return str(val)


def _signed(val: Any, suffix: str = "%", decimals: int = 2) -> str:
    if val is None:
        return "N/A"
    try:
        v = float(val)
        sign = "+" if v > 0 else ""
        return f"{sign}{v:.{decimals}f}{suffix}"
    except (TypeError, ValueError):
        return str(val)


def _signal_color(text: str):
    """Return a hex colour based on signal text."""
    t = (text or "").lower()
    if any(x in t for x in ("bull", "overbought", "above", "strong", "positive", "good", "excellent", "wide")):
        return "#0a7a1e"
    if any(x in t for x in ("bear", "oversold", "below", "weak", "negative", "poor", "high risk", "no clear")):
        return "#cc1a1a"
    return "#3a3a3a"


# ── Main report builder ────────────────────────────────────────────────────────

def build_report(
    symbol: str,
    quote: Optional[Dict]        = None,
    fundamentals: Optional[Dict] = None,
    technical: Optional[Dict]    = None,
    risk: Optional[Dict]         = None,
    patterns: Optional[Dict]     = None,
    sentiment: Optional[Dict]    = None,
    narrative: str               = "",
    output_dir: str              = "data",
) -> str:
    """
    Generate a PDF analysis report and save it to output_dir.

    Args:
        symbol:      Ticker symbol (used in filename).
        quote:       Result from get_quote().
        fundamentals:Result from fundamental_analysis().
        technical:   Result from technical_analysis().
        risk:        Result from risk_score().
        patterns:    Result from pattern_detection().
        sentiment:   Result from sentiment_analysis().
        narrative:   LLM-generated plain-language summary.
        output_dir:  Directory to save the PDF (created if needed).

    Returns:
        Absolute path to the generated PDF file.
    """
    _rl()  # ensure reportlab is installed

    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import cm, mm
    from reportlab.lib import colors
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
        HRFlowable, PageBreak,
    )

    os.makedirs(output_dir, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename  = f"analysis_{symbol.upper()}_{timestamp}.pdf"
    filepath  = os.path.join(output_dir, filename)

    PAGE_W, PAGE_H = A4
    MARGIN = 1.8 * cm
    CONTENT_W = PAGE_W - 2 * MARGIN

    doc = SimpleDocTemplate(
        filepath,
        pagesize=A4,
        leftMargin=MARGIN,
        rightMargin=MARGIN,
        topMargin=MARGIN,
        bottomMargin=1.5 * cm,
        title=f"Stock Analysis — {symbol.upper()}",
        author="OctaMind",
        subject="Stock Market Analysis Report (Informational Only)",
    )

    st = _styles()

    def rgb(t):
        return colors.Color(*t)

    story = []

    # ── COVER PAGE ──────────────────────────────────────────────────────────────
    # Navy banner
    cover_data = [[
        Paragraph(f"📊  OctaMind Stock Analysis Report", st["title"])
    ]]
    cover_table = Table(cover_data, colWidths=[CONTENT_W])
    cover_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), rgb(_NAVY)),
        ("TOPPADDING",    (0, 0), (-1, -1), 22),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 22),
        ("LEFTPADDING",   (0, 0), (-1, -1), 12),
    ]))
    story.append(cover_table)
    story.append(Spacer(1, 0.4 * cm))

    # Company info box
    company_name = (quote or {}).get("name", symbol.upper())
    sector        = (quote or fundamentals or {}).get("sector", "N/A")
    currency      = (quote or {}).get("currency", "USD")
    price_str     = _fmt((quote or {}).get("price"), suffix=f" {currency}", decimals=2)
    chg_str       = _signed((quote or {}).get("change_pct"))
    generated_on  = datetime.now().strftime("%A, %d %B %Y  %H:%M")

    info_data = [
        ["Symbol", symbol.upper(), "Price", price_str],
        ["Company", company_name,  "Day Change", chg_str],
        ["Sector",  sector,        "Generated", generated_on],
    ]
    info_table = Table(info_data, colWidths=[CONTENT_W * 0.18, CONTENT_W * 0.42, CONTENT_W * 0.18, CONTENT_W * 0.22])
    info_table.setStyle(TableStyle([
        ("BACKGROUND",  (0, 0), (0, -1), rgb(_TEAL)),
        ("BACKGROUND",  (2, 0), (2, -1), rgb(_TEAL)),
        ("TEXTCOLOR",   (0, 0), (0, -1), colors.white),
        ("TEXTCOLOR",   (2, 0), (2, -1), colors.white),
        ("FONTNAME",    (0, 0), (-1, -1), "Helvetica"),
        ("FONTNAME",    (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME",    (2, 0), (2, -1), "Helvetica-Bold"),
        ("FONTSIZE",    (0, 0), (-1, -1), 9),
        ("GRID",        (0, 0), (-1, -1), 0.25, rgb(_GRAY)),
        ("TOPPADDING",  (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(info_table)
    story.append(Spacer(1, 0.5 * cm))

    # Disclaimer box
    disc_box = Table([[Paragraph(_DISCLAIMER, st["disc_style"])]], colWidths=[CONTENT_W])
    disc_box.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.Color(1.0, 0.95, 0.85)),
        ("BOX",        (0, 0), (-1, -1), 1.0, rgb(_ORANGE)),
        ("TOPPADDING",    (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("LEFTPADDING",   (0, 0), (-1, -1), 10),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 10),
    ]))
    story.append(disc_box)
    story.append(PageBreak())

    # ── SECTION 1: EXECUTIVE SUMMARY ───────────────────────────────────────────
    story.append(Paragraph("1.  Executive Summary", st["section"]))
    story.append(Spacer(1, 0.2 * cm))
    if narrative:
        # Split into paragraphs for readability
        for para in narrative.split("\n"):
            para = para.strip()
            if para:
                story.append(Paragraph(para.replace("**", ""), st["body"]))
    else:
        story.append(Paragraph("No narrative summary was generated.", st["body"]))
    story.append(Spacer(1, 0.3 * cm))

    # ── SECTION 2: MARKET SNAPSHOT ─────────────────────────────────────────────
    story.append(Paragraph("2.  Market Snapshot", st["section"]))
    story.append(Spacer(1, 0.2 * cm))
    if quote and quote.get("status") == "success":
        q = quote
        snap_data = [
            ["Metric", "Value", "Metric", "Value"],
            ["Current Price",  _fmt(q.get("price"),         suffix=f" {q.get('currency','')}", decimals=2),
             "Volume",         _fmt(q.get("volume"),         suffix="", decimals=0, na="N/A")],
            ["Day Change",     _signed(q.get("change_pct")),
             "Avg Volume",     _fmt(q.get("avg_volume"),     suffix="", decimals=0, na="N/A")],
            ["Market Cap",     _fmt(q.get("market_cap"),     suffix="", decimals=0, na="N/A"),
             "P/E Ratio",      _fmt(q.get("pe_ratio"),       decimals=2)],
            ["52W High",       _fmt(q.get("52w_high"),       decimals=2),
             "52W Low",        _fmt(q.get("52w_low"),        decimals=2)],
            ["EPS (TTM)",      _fmt(q.get("eps"),            decimals=2),
             "Dividend Yield", _fmt(q.get("dividend_yield"), suffix="%", decimals=2)],
            ["Sector",         q.get("sector", "N/A"),
             "Industry",       q.get("industry", "N/A")],
        ]
        col_w = [CONTENT_W * 0.22, CONTENT_W * 0.28, CONTENT_W * 0.22, CONTENT_W * 0.28]
        story.append(_table(snap_data, col_w))

    # ── SECTION 3: FUNDAMENTAL ANALYSIS ────────────────────────────────────────
    story.append(Spacer(1, 0.3 * cm))
    story.append(Paragraph("3.  Fundamental Analysis  (Warren Buffett Quality Framework)", st["section"]))
    story.append(Spacer(1, 0.2 * cm))

    if fundamentals and fundamentals.get("status") == "success":
        fa = fundamentals

        # Score banner
        moat_bar   = _score_bar(fa.get("moat_score", 0),    10, fa.get("moat_label", ""))
        qual_bar   = _score_bar(fa.get("quality_score", 0), 10, fa.get("quality_label", ""))
        score_data = [
            ["Moat Score",    moat_bar],
            ["Quality Score", qual_bar],
        ]
        sc_table = Table(score_data, colWidths=[CONTENT_W * 0.25, CONTENT_W * 0.75])
        sc_table.setStyle(TableStyle([
            ("BACKGROUND",  (0, 0), (0, -1), rgb(_TEAL)),
            ("TEXTCOLOR",   (0, 0), (0, -1), colors.white),
            ("FONTNAME",    (0, 0), (-1, -1), "Helvetica"),
            ("FONTNAME",    (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTSIZE",    (0, 0), (-1, -1), 9),
            ("GRID",        (0, 0), (-1, -1), 0.25, rgb(_GRAY)),
            ("TOPPADDING",  (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("FONTNAME",    (1, 0), (1, -1), "Courier"),
        ]))
        story.append(sc_table)
        story.append(Spacer(1, 0.25 * cm))

        # Metrics table
        fund_data = [
            ["Quality", "Value", "Safety / Value", "Value"],
            ["Return on Equity",        _fmt(fa.get("roe_pct"),          suffix="%", decimals=1),
             "Debt / Equity",           _fmt(fa.get("debt_to_equity"),   decimals=2)],
            ["Return on Assets",        _fmt(fa.get("roa_pct"),          suffix="%", decimals=1),
             "Current Ratio",           _fmt(fa.get("current_ratio"),    decimals=2)],
            ["Gross Margin",            _fmt(fa.get("gross_margin_pct"), suffix="%", decimals=1),
             "Quick Ratio",             _fmt(fa.get("quick_ratio"),      decimals=2)],
            ["Operating Margin",        _fmt(fa.get("operating_margin_pct"), suffix="%", decimals=1),
             "P/E Ratio",               _fmt(fa.get("pe_ratio"),         decimals=2)],
            ["Net Profit Margin",       _fmt(fa.get("net_margin_pct"),   suffix="%", decimals=1),
             "Forward P/E",             _fmt(fa.get("forward_pe"),       decimals=2)],
            ["FCF Yield",               _fmt(fa.get("fcf_yield_pct"),    suffix="%", decimals=2),
             "Price / Book",            _fmt(fa.get("pb_ratio"),         decimals=2)],
            ["Earnings Growth (YoY)",   _fmt(fa.get("earnings_growth_yoy_pct"), suffix="%", decimals=1),
             "PEG Ratio",               _fmt(fa.get("peg_ratio"),        decimals=2)],
            ["Revenue Growth (YoY)",    _fmt(fa.get("revenue_growth_yoy_pct"),  suffix="%", decimals=1),
             "EV / EBITDA",             _fmt(fa.get("ev_ebitda"),        decimals=2)],
            ["Dividend Yield",          _fmt(fa.get("dividend_yield_pct"), suffix="%", decimals=2),
             "Payout Ratio",            _fmt(fa.get("payout_ratio_pct"), suffix="%", decimals=1)],
        ]
        col_w = [CONTENT_W * 0.27, CONTENT_W * 0.23, CONTENT_W * 0.27, CONTENT_W * 0.23]
        story.append(_table(fund_data, col_w))

        # Moat breakdown
        story.append(Spacer(1, 0.2 * cm))
        story.append(Paragraph("Moat Signal Breakdown:", st["bold"]))
        bdown = fa.get("moat_breakdown", {})
        for key, val in bdown.items():
            story.append(Paragraph(f"  • {key.replace('_', ' ').title()}: {val}", st["body_small"]))

    # ── SECTION 4: TECHNICAL ANALYSIS ──────────────────────────────────────────
    story.append(Spacer(1, 0.3 * cm))
    story.append(Paragraph("4.  Technical Analysis", st["section"]))
    story.append(Spacer(1, 0.2 * cm))

    if technical and technical.get("status") == "success":
        tc = technical
        rsi  = tc.get("rsi", {})
        macd = tc.get("macd", {})
        bb   = tc.get("bollinger", {})
        ma   = tc.get("moving_averages", {})

        tech_data = [
            ["Indicator", "Value", "Signal", "Interpretation"],
            ["RSI (14)",
             _fmt(rsi.get("value"), decimals=2),
             rsi.get("signal", "N/A").title(),
             "Overbought >70, Oversold <30"],
            ["MACD",
             _fmt(macd.get("macd"), decimals=4),
             macd.get("signal_text", "N/A").title(),
             f"Signal line: {_fmt(macd.get('signal'), decimals=4)}"],
            ["MACD Histogram",
             _fmt(macd.get("histogram"), decimals=4),
             "Positive=Bullish" if (macd.get("histogram") or 0) > 0 else "Negative=Bearish",
             "Divergence from signal line"],
            ["Bollinger Upper",
             _fmt(bb.get("upper"), decimals=2),
             bb.get("signal", "N/A").title(),
             f"Middle: {_fmt(bb.get('middle'), decimals=2)}  Lower: {_fmt(bb.get('lower'), decimals=2)}"],
            ["SMA 20",
             _fmt(ma.get("sma20"), decimals=2),
             f"Price {ma.get('vs_sma20','N/A')} SMA20",
             "20-day simple moving average"],
            ["SMA 50",
             _fmt(ma.get("sma50"), decimals=2),
             f"Price {ma.get('vs_sma50','N/A')} SMA50",
             "50-day simple moving average"],
            ["SMA 200",
             _fmt(ma.get("sma200"), decimals=2),
             f"Price {ma.get('vs_sma200','N/A')} SMA200",
             "200-day simple moving average"],
        ]
        col_w = [CONTENT_W * 0.19, CONTENT_W * 0.16, CONTENT_W * 0.20, CONTENT_W * 0.45]
        story.append(_table(tech_data, col_w))

    # ── SECTION 5: RISK ASSESSMENT ──────────────────────────────────────────────
    story.append(Spacer(1, 0.3 * cm))
    story.append(Paragraph("5.  Risk Assessment", st["section"]))
    story.append(Spacer(1, 0.2 * cm))

    if risk and risk.get("status") == "success":
        r = risk
        risk_score_val = r.get("risk_score", 0)
        risk_bar = _score_bar(risk_score_val, 10, r.get("risk_level", ""))

        risk_banner_data = [["Risk Score", risk_bar]]
        rb_table = Table(risk_banner_data, colWidths=[CONTENT_W * 0.20, CONTENT_W * 0.80])
        rb_table.setStyle(TableStyle([
            ("BACKGROUND",  (0, 0), (0, -1), rgb(_RED if risk_score_val >= 7 else (_ORANGE if risk_score_val >= 5 else _GREEN))),
            ("TEXTCOLOR",   (0, 0), (0, -1), colors.white),
            ("FONTNAME",    (0, 0), (-1, -1), "Helvetica"),
            ("FONTNAME",    (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTSIZE",    (0, 0), (-1, -1), 9),
            ("GRID",        (0, 0), (-1, -1), 0.25, rgb(_GRAY)),
            ("TOPPADDING",  (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("FONTNAME",    (1, 0), (1, -1), "Courier"),
        ]))
        story.append(rb_table)
        story.append(Spacer(1, 0.25 * cm))

        risk_data = [
            ["Risk Metric", "Value", "Risk Metric", "Value"],
            ["Annual Volatility",   _fmt(r.get("annual_volatility_pct"),   suffix="%"),
             "Sharpe Ratio (1Y)",   _fmt(r.get("sharpe_ratio"),            decimals=3)],
            ["Beta vs SPY",         _fmt(r.get("beta"),                    decimals=3),
             "Sortino Ratio",       _fmt(r.get("sortino_ratio"),           decimals=3)],
            ["VaR 95% (daily)",     _fmt(r.get("var_95_daily_pct"),        suffix="%"),
             "Max Drawdown",        _fmt(r.get("max_drawdown_pct"),        suffix="%", decimals=2)],
            ["Annual Return",       _fmt(r.get("annual_return_pct"),       suffix="%"),
             "Calmar Ratio",        _fmt(r.get("calmar_ratio"),            decimals=3)],
        ]
        col_w = [CONTENT_W * 0.27, CONTENT_W * 0.23, CONTENT_W * 0.27, CONTENT_W * 0.23]
        story.append(_table(risk_data, col_w))

        story.append(Spacer(1, 0.15 * cm))
        story.append(Paragraph(
            "Risk Score Methodology: composite of normalised annual volatility (40%), "
            "Beta vs SPY (30%), and daily VaR 95% (30%).  Score 1=low risk, 10=very high risk.",
            st["body_small"]
        ))

    # ── SECTION 6: PATTERN DETECTION ───────────────────────────────────────────
    story.append(Spacer(1, 0.3 * cm))
    story.append(Paragraph("6.  Chart Pattern Detection", st["section"]))
    story.append(Spacer(1, 0.2 * cm))

    if patterns and patterns.get("status") == "success":
        pt = patterns
        pat_data = [
            ["Metric", "Value"],
            ["Trend",           pt.get("trend", "N/A").title()],
            ["Support Level",   _fmt(pt.get("support"),     decimals=2)],
            ["Resistance Level",_fmt(pt.get("resistance"),  decimals=2)],
            ["Latest Close",    _fmt(pt.get("latest_close"),decimals=2)],
            ["Price Position",  pt.get("price_position", "N/A").title()],
        ]
        story.append(_table(pat_data, [CONTENT_W * 0.35, CONTENT_W * 0.65]))

        story.append(Spacer(1, 0.2 * cm))
        story.append(Paragraph("Detected Candlestick Patterns:", st["bold"]))
        for p in (pt.get("patterns") or ["None detected"]):
            story.append(Paragraph(f"  • {p}", st["body"]))

    # ── SECTION 7: NEWS SENTIMENT ───────────────────────────────────────────────
    story.append(Spacer(1, 0.3 * cm))
    story.append(Paragraph("7.  News Sentiment Analysis", st["section"]))
    story.append(Spacer(1, 0.2 * cm))

    if sentiment and sentiment.get("status") == "success":
        sn = sentiment
        overall = sn.get("overall_sentiment", "N/A")
        sn_color = rgb(_GREEN if overall == "Positive" else (_RED if overall == "Negative" else _ORANGE))

        sn_summary = [
            ["Overall Sentiment", "Score",   "Positive", "Neutral", "Negative"],
            [overall,
             _fmt(sn.get("aggregate_score"), decimals=3),
             str(sn.get("positive_headlines", 0)),
             str(sn.get("neutral_headlines", 0)),
             str(sn.get("negative_headlines", 0))],
        ]
        sn_table = Table(sn_summary, colWidths=[
            CONTENT_W * 0.25, CONTENT_W * 0.15,
            CONTENT_W * 0.20, CONTENT_W * 0.20, CONTENT_W * 0.20,
        ])
        sn_table.setStyle(TableStyle([
            ("BACKGROUND",  (0, 0), (-1, 0), rgb(_NAVY)),
            ("TEXTCOLOR",   (0, 0), (-1, 0), colors.white),
            ("BACKGROUND",  (0, 1), (0, 1), sn_color),
            ("FONTNAME",    (0, 0), (-1, -1), "Helvetica"),
            ("FONTNAME",    (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTNAME",    (0, 1), (0, 1), "Helvetica-Bold"),
            ("FONTSIZE",    (0, 0), (-1, -1), 9),
            ("GRID",        (0, 0), (-1, -1), 0.25, rgb(_GRAY)),
            ("TOPPADDING",  (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("ALIGN",       (0, 1), (0, 1), "CENTER"),
            ("TEXTCOLOR",   (0, 1), (0, 1), colors.white),
        ]))
        story.append(sn_table)

        # Engine indicator
        engine = sn.get("sentiment_engine", "keyword")
        engine_label = (
            "✓ LLM-classified (context-aware, handles sarcasm and nuance)"
            if engine == "llm" else
            "⚠ Keyword NLP fallback (LLM unavailable)"
        )
        story.append(Spacer(1, 0.1 * cm))
        story.append(Paragraph(f"Analysis engine: {engine_label}", st["body_small"]))

        # Top headlines
        story.append(Spacer(1, 0.15 * cm))
        story.append(Paragraph("Recent Headlines (sample):", st["bold"]))
        for item in (sn.get("news_items") or [])[:8]:
            label = item.get("sentiment", "Neutral")
            icon  = "▲" if label == "Positive" else ("▼" if label == "Negative" else "–")
            pub   = item.get("published", "")
            conf  = item.get("llm_confidence")
            conf_str = f" [{conf:.0%}]" if conf is not None else ""
            story.append(Paragraph(
                f"  {icon} [{pub}] {item.get('title', '')}{conf_str}  "
                f"<font color='grey'>({item.get('publisher','')})</font>",
                st["body_small"]
            ))

        story.append(Spacer(1, 0.15 * cm))
        story.append(Paragraph(
            sn.get("note", "Indicative only."),
            st["body_small"]
        ))

    # ── FOOTER DISCLAIMER ──────────────────────────────────────────────────────
    story.append(Spacer(1, 0.5 * cm))
    story.append(HRFlowable(width=CONTENT_W, thickness=0.5, color=rgb(_GRAY)))
    story.append(Spacer(1, 0.1 * cm))
    story.append(Paragraph(_DISCLAIMER, st["disc_style"]))

    # ── BUILD PDF ──────────────────────────────────────────────────────────────
    doc.build(story)
    return os.path.abspath(filepath)
