"""
Stock Analysis Report Generator — PDF via reportlab
=====================================================

Produces a structured, multi-section PDF analysis report.

Inputs  : structured dicts from all stock analysis tools + LLM narrative
Output  : PDF file saved to disk, path returned

Layout:
  Cover page  — name, date, symbol, SEBI/general disclaimer
  Section 1   — Executive Summary (LLM narrative)
  Section 2   — Market Snapshot (current quote)
  Section 3   — Fundamental Analysis (Buffett metrics, moat score)
  Section 4   — Technical Analysis (RSI/MACD/Bollinger/SMA)
  Section 5   — Risk Assessment (volatility/Beta/VaR/Sharpe/MaxDD)
  Section 6   — Chart Pattern Detection
  Section 7   — News Sentiment
  Footer      — disclaimer on every page

NO buy/sell recommendations. NO price targets. Informational only.

Requires: pip install reportlab
"""
from __future__ import annotations

import os
from datetime import datetime
from typing import Any, Dict, List, Optional

# ── Reportlab imports (lazy, with clear error) ─────────────────────────────────

def _rl():
    try:
        import reportlab
        return reportlab
    except ImportError as exc:
        raise ImportError("reportlab is not installed. Run: pip install reportlab") from exc


# ── Colour palette (Octa Bot — modern fintech) ────────────────────────────────

_NAVY    = (0.05, 0.09, 0.20)   # rich deep navy  — headers / cover bg
_SLATE   = (0.18, 0.30, 0.45)   # mid slate-blue   — subtle sub-accents
_TEAL    = (0.00, 0.50, 0.56)   # muted teal       — accent rule / header bar
_TEAL2   = (0.04, 0.34, 0.44)   # dark teal        — table header fill
_GOLD    = (0.72, 0.50, 0.03)   # warm amber-gold  — disclaimers / warnings
_LIGHT   = (0.96, 0.97, 0.99)   # near-white blue  — alternating table rows
_PANEL   = (0.97, 0.975, 1.00)  # very light panel backgrounds
_WHITE   = (1.00, 1.00, 1.00)
_RED     = (0.72, 0.08, 0.12)
_GREEN   = (0.04, 0.48, 0.22)
_ORANGE  = (0.80, 0.40, 0.04)   # kept for backward-compat
_GRAY    = (0.45, 0.49, 0.55)
_LGRAY   = (0.84, 0.86, 0.90)   # light gray — table grid lines
_DIVIDER = (0.90, 0.91, 0.94)   # very pale — inner row dividers
_BLACK   = (0.10, 0.12, 0.15)

_DISCLAIMER = (
    "IMPORTANT DISCLAIMER: This report is generated by Octa Bot for informational and "
    "educational purposes ONLY. It does NOT constitute financial advice, investment advice, "
    "trading advice, or any other type of advice. No buy, sell, or hold recommendation is "
    "made for any security. Past performance is not indicative of future results. "
    "Investments in securities are subject to market risk. Please read all scheme-related "
    "documents carefully and consult a SEBI-registered investment advisor before making any "
    "investment decision. Octa Bot and its operators are NOT registered with SEBI or any "
    "regulatory authority as investment advisors."
)


# ── Logo finder ──────────────────────────────────────────────────────────────

def _find_logo() -> Optional[str]:
    """Walk up from this module to find docs/octa_bot.jpg in the project root."""
    here = os.path.dirname(os.path.abspath(__file__))
    for _ in range(6):
        candidate = os.path.join(here, "docs", "octa_bot.jpg")
        if os.path.exists(candidate):
            return candidate
        here = os.path.dirname(here)
    return None


# ── Running page header/footer callback ────────────────────────────────────────

def _make_page_cb(logo_path, symbol, generated_on, page_w, page_h, margin):
    """Return a canvas callback that draws a footer (and header on pages 2+)."""
    def cb(canvas, doc):
        from reportlab.lib.units import cm
        canvas.saveState()

        # ── Footer ──────────────────────────────────────────────────────────
        y_line = 0.95 * cm
        canvas.setStrokeColorRGB(*_TEAL)
        canvas.setLineWidth(0.4)
        canvas.line(margin, y_line, page_w - margin, y_line)

        canvas.setFont("Helvetica", 6.5)
        canvas.setFillColorRGB(*_GRAY)
        canvas.drawString(margin, y_line - 0.30 * cm,
            "Octa Bot Platform  |  For informational purposes only")
        canvas.drawCentredString(page_w / 2, y_line - 0.30 * cm,
            f"Page {doc.page}")
        canvas.drawRightString(page_w - margin, y_line - 0.30 * cm,
            f"{symbol.upper()}  |  {generated_on}")

        # ── Header on pages 2+ ───────────────────────────────────────────────
        if doc.page > 1:
            y_top = page_h - margin * 0.60
            # thin teal rule
            canvas.setStrokeColorRGB(*_TEAL)
            canvas.setLineWidth(0.4)
            canvas.line(margin, y_top - 0.05 * cm, page_w - margin, y_top - 0.05 * cm)
            # Logo thumbnail
            logo_x = margin
            if logo_path and os.path.exists(logo_path):
                icon_h = 0.55 * cm
                try:
                    canvas.drawImage(logo_path, logo_x, y_top - icon_h,
                                     width=icon_h, height=icon_h,
                                     preserveAspectRatio=True, anchor="sw")
                    logo_x += icon_h + 0.15 * cm
                except Exception:  # noqa: BLE001
                    pass
            canvas.setFont("Helvetica-Bold", 7.5)
            canvas.setFillColorRGB(*_NAVY)
            canvas.drawString(logo_x, y_top - 0.38 * cm, "Octa Bot  |  Stock Analysis Report")
            canvas.setFont("Helvetica", 7.5)
            canvas.setFillColorRGB(*_TEAL)
            canvas.drawRightString(page_w - margin, y_top - 0.38 * cm, symbol.upper())

        canvas.restoreState()
    return cb


# ── Section header helper ─────────────────────────────────────────────────────

def _section_header(title: str, styles: dict, content_w: float):
    """Return a refined section header: narrow teal accent | navy title band."""
    from reportlab.platypus import Table, TableStyle, Paragraph
    from reportlab.lib import colors

    def rgb(t):
        return colors.Color(*t)

    ACCENT_PTS = 5          # width of the left colour bar in points
    data = [["", Paragraph(title, styles["section"])]]
    t = Table(data, colWidths=[ACCENT_PTS, content_w - ACCENT_PTS])
    t.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (0, -1), rgb(_TEAL)),
        ("BACKGROUND",    (1, 0), (1, -1), rgb(_NAVY)),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING",    (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING",   (0, 0), (0, -1), 0),
        ("LEFTPADDING",   (1, 0), (1, -1), 10),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 8),
    ]))
    return t


# ── Helper: build paragraph style ──────────────────────────────────────────────

def _styles():
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.enums import TA_LEFT
    from reportlab.lib import colors

    base = getSampleStyleSheet()

    def rgb(t):
        return colors.Color(*t)

    styles = {}

    styles["title"] = ParagraphStyle(
        "OmTitle",
        parent=base["Normal"],
        fontName="Helvetica-Bold",
        fontSize=20,
        textColor=rgb(_WHITE),
        alignment=TA_LEFT,
        leading=26,
        spaceAfter=4,
    )
    styles["subtitle"] = ParagraphStyle(
        "OmSubtitle",
        parent=base["Normal"],
        fontName="Helvetica",
        fontSize=9.5,
        textColor=colors.Color(0.72, 0.82, 0.90),  # cool pale blue
        alignment=TA_LEFT,
        leading=13,
        spaceAfter=2,
    )
    styles["section"] = ParagraphStyle(
        "OmSection",
        parent=base["Normal"],
        fontName="Helvetica-Bold",
        fontSize=9.5,
        textColor=rgb(_WHITE),
        leading=14,
        spaceBefore=0,
        spaceAfter=0,
        leftIndent=10,
        rightIndent=8,
    )
    styles["body"] = ParagraphStyle(
        "OmBody",
        parent=base["Normal"],
        fontSize=9,
        textColor=rgb(_BLACK),
        leading=15,
        spaceAfter=5,
    )
    styles["body_small"] = ParagraphStyle(
        "OmBodySmall",
        parent=base["Normal"],
        fontSize=7.5,
        textColor=rgb(_GRAY),
        leading=11,
        spaceAfter=2,
    )
    styles["disc_style"] = ParagraphStyle(
        "OmDisc",
        parent=base["Normal"],
        fontSize=6.5,
        textColor=colors.Color(0.42, 0.26, 0.02),
        leading=10,
    )
    styles["insight"] = ParagraphStyle(
        "OmInsight",
        parent=base["Normal"],
        fontSize=8.5,
        textColor=rgb(_NAVY),
        leading=13,
        leftIndent=8,
        spaceAfter=3,
    )
    styles["kv_key"] = ParagraphStyle(
        "OmKVKey",
        parent=base["Normal"],
        fontSize=8.5,
        textColor=rgb(_GRAY),
        leading=12,
    )
    styles["kv_val"] = ParagraphStyle(
        "OmKVVal",
        parent=base["Normal"],
        fontSize=8.5,
        textColor=rgb(_BLACK),
        leading=12,
    )
    styles["bold"] = ParagraphStyle(
        "OmBold",
        parent=base["Normal"],
        fontSize=9,
        textColor=rgb(_BLACK),
        leading=13,
        fontName="Helvetica-Bold",
    )
    styles["snap_label"] = ParagraphStyle(
        "OmSnapLabel",
        parent=base["Normal"],
        fontSize=6.5,
        textColor=rgb(_GRAY),
        fontName="Helvetica-Bold",
        leading=9,
        spaceAfter=0,
    )
    styles["snap_value"] = ParagraphStyle(
        "OmSnapValue",
        parent=base["Normal"],
        fontSize=11,
        fontName="Helvetica-Bold",
        textColor=rgb(_BLACK),
        leading=14,
        spaceAfter=0,
    )
    return styles


# ── Helper: coloured table ─────────────────────────────────────────────────────

def _table(data: List[List[str]], col_widths, header_bg=None):
    """Build a reportlab Table with word-wrapping cells and alternating row shading."""
    from reportlab.platypus import Table, TableStyle, Paragraph
    from reportlab.lib.styles import ParagraphStyle
    from reportlab.lib import colors

    def rgb(t):
        return colors.Color(*t)

    hbg = rgb(header_bg or _TEAL2)

    # Paragraph styles used for cell text — ensures word-wrap in every column
    _cs = ParagraphStyle("_tc",  fontName="Helvetica",      fontSize=8.5, leading=12,
                         textColor=rgb(_BLACK), spaceAfter=0, spaceBefore=0)
    _hs = ParagraphStyle("_th",  fontName="Helvetica-Bold", fontSize=8.0, leading=11,
                         textColor=colors.white, spaceAfter=0, spaceBefore=0)

    wrapped = []
    for ri, row in enumerate(data):
        wr = []
        for cell in row:
            if isinstance(cell, str):
                wr.append(Paragraph(cell, _hs if ri == 0 else _cs))
            else:
                wr.append(cell)   # already a Paragraph / flowable
        wrapped.append(wr)

    style_cmds = [
        # Header row background
        ("BACKGROUND",    (0, 0), (-1, 0),  hbg),
        ("LINEBELOW",     (0, 0), (-1, 0),  1.0, rgb(_TEAL)),
        # Data rows
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, rgb(_LIGHT)]),
        # Grid
        ("LINEABOVE",     (0, 1), (-1, -1), 0.25, rgb(_DIVIDER)),
        ("LINEBEFORE",    (1, 0), (-1, -1), 0.25, rgb(_DIVIDER)),
        # Outer border
        ("BOX",           (0, 0), (-1, -1), 0.5,  rgb(_LGRAY)),
        # Padding & alignment
        ("VALIGN",        (0, 0), (-1, 0),  "MIDDLE"),   # header centred
        ("VALIGN",        (0, 1), (-1, -1), "TOP"),       # data rows top-aligned
        ("TOPPADDING",    (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING",   (0, 0), (-1, -1), 8),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 8),
    ]
    t = Table(wrapped, colWidths=col_widths)
    t.setStyle(TableStyle(style_cmds))
    return t


# ── Helper: score badge ────────────────────────────────────────────────────────

def _score_bar(score: float, max_score: float = 10, label: str = "") -> str:
    # Use plain ASCII characters — Unicode block elements are not in reportlab's
    # built-in Helvetica/Times fonts and render as 'n' or replacement chars.
    filled = int(round(score))
    empty  = int(max_score) - filled
    bar    = "#" * filled + "-" * empty
    return f"[{bar}]  {score}/{int(max_score)}  {label}"


# ── Null-safe formatting ────────────────────────────────────────────────────────

def _fmt(val: Any, suffix: str = "", decimals: int = 2, na: str = "N/A") -> str:
    if val is None:
        return na
    try:
        return f"{float(val):.{decimals}f}{suffix}"
    except (TypeError, ValueError):
        return str(val)


def _signed(val: Any, suffix: str = "%", decimals: int = 2) -> str:
    if val is None:
        return "N/A"
    try:
        v = float(val)
        sign = "+" if v > 0 else ""
        return f"{sign}{v:.{decimals}f}{suffix}"
    except (TypeError, ValueError):
        return str(val)


def _signal_color(text: str):
    """Return a hex colour based on signal text."""
    t = (text or "").lower()
    if any(x in t for x in ("bull", "overbought", "above", "strong", "positive", "good", "excellent", "wide")):
        return "#0a7a1e"
    if any(x in t for x in ("bear", "oversold", "below", "weak", "negative", "poor", "high risk", "no clear")):
        return "#cc1a1a"
    return "#3a3a3a"


def _rule_based_summary(
    quote:        Optional[Dict],
    technical:    Optional[Dict],
    fundamentals: Optional[Dict],
    risk:         Optional[Dict],
    sentiment:    Optional[Dict],
    patterns:     Optional[Dict],
) -> str:
    """
    Generate a concise 5-bullet executive summary from available data when an
    LLM narrative is not provided.  Each bullet is one plain-English sentence.
    """
    lines = []
    tech = technical or {}
    fund = fundamentals or {}
    rsk  = risk or {}
    sent = sentiment or {}
    pats = patterns or {}

    # 1. Trend & price position
    trend = tech.get("trend", "") or pats.get("trend", "")
    sma50  = tech.get("sma_50")
    sma200 = tech.get("sma_200")
    price  = (quote or {}).get("price")
    if trend:
        sma_clause = ""
        if sma50 and price:
            sma_clause = f", trading {'above' if price >= sma50 else 'below'} its 50-day average"
        if sma200 and price:
            sma_clause += f" and {'above' if price >= sma200 else 'below'} its 200-day average"
        lines.append(f"Stock is in a {trend} trend{sma_clause}.")

    # 2. RSI signal (rsi may be a float or a dict with {"value": ..., "signal": ...})
    _rsi_raw = tech.get("rsi")
    if isinstance(_rsi_raw, dict):
        rsi_val = _rsi_raw.get("value")
        rsi_sig = (_rsi_raw.get("signal") or "").lower()
    elif _rsi_raw is not None:
        rsi_val = float(_rsi_raw)
        rsi_sig = "overbought" if rsi_val >= 70 else ("oversold" if rsi_val <= 30 else
                  "near overbought" if rsi_val >= 65 else "near oversold" if rsi_val <= 35 else "neutral")
    else:
        rsi_val = rsi_sig = None
    if rsi_val is not None:
        if rsi_sig in ("overbought", "near overbought"):
            lines.append(f"RSI at {rsi_val:.1f} — approaching overbought territory; short-term pullback risk elevated.")
        elif rsi_sig in ("oversold", "near oversold"):
            lines.append(f"RSI at {rsi_val:.1f} — near oversold zone; potential mean-reversion opportunity.")
        else:
            lines.append(f"RSI at {rsi_val:.1f} — momentum neutral, no extreme reading.")

    # 3. Risk assessment  (supports both old and new field names)
    if rsk.get("status") == "success":
        rl  = rsk.get("risk_label") or rsk.get("risk_level") or rsk.get("overall_risk") or ""
        rs  = rsk.get("risk_score")
        vol = rsk.get("volatility") or rsk.get("annual_volatility_pct")
        dd  = rsk.get("max_drawdown") or rsk.get("max_drawdown_pct")
        rs_str  = f" ({rs}/10)" if rs is not None else ""
        vol_str = f"; annual volatility {float(vol):.1f}%" if vol is not None else ""
        dd_str  = f", max drawdown {float(dd):.1f}%" if dd is not None else ""
        if rl:
            lines.append(f"Risk profile: {rl}{rs_str}{vol_str}{dd_str}.")

    # 4. Quality / fundamentals
    if fund.get("status") == "success":
        qs = fund.get("quality_score")
        ql = fund.get("quality_label", "")
        de = fund.get("debt_to_equity")
        eg = fund.get("earnings_growth_5yr") or fund.get("earnings_growth_yoy_pct")
        rv = fund.get("revenue_growth_yoy_pct")
        # Use gross_margin_pct (correct key); fall back to operating_margin_pct with proper label
        gm = fund.get("gross_margin_pct")
        gm_label = "gross margin"
        if gm is None:
            gm = fund.get("operating_margin_pct")
            gm_label = "operating margin"
        notes = []
        if gm is not None:
            notes.append(f"{gm_label} {float(gm):.1f}%")
        if de is not None:
            notes.append(f"D/E {float(de):.2f}")
        if eg is not None:
            eg_lbl = "strong" if float(eg) >= 15 else ("positive" if float(eg) >= 0 else "negative")
            notes.append(f"{eg_lbl} earnings growth")
        if rv is not None:
            notes.append(f"revenue growth {float(rv):.1f}%")
        qual_note = f" — {', '.join(notes)}" if notes else ""
        if qs is not None:
            lines.append(f"Quality score {qs}/10 ({ql}){qual_note}.")

    # 5. Sentiment
    if sent.get("status") == "success":
        overall = sent.get("overall_sentiment", "")
        score   = sent.get("aggregate_score") or sent.get("sentiment_score")
        count   = (sent.get("article_count")
                   or (sent.get("positive_headlines", 0)
                       + sent.get("neutral_headlines", 0)
                       + sent.get("negative_headlines", 0)))
        if overall:
            score_str = f" (score {score:.2f})" if score is not None else ""
            count_str = f" across {count} recent articles" if count else ""
            lines.append(f"News sentiment {overall.lower()}{score_str}{count_str}.")

    if not lines:
        return ""
    return "\n".join(f"• {ln}" for ln in lines)


# ── Main report builder ────────────────────────────────────────────────────────

def build_report(
    symbol: str,
    quote: Optional[Dict]        = None,
    fundamentals: Optional[Dict] = None,
    technical: Optional[Dict]    = None,
    risk: Optional[Dict]         = None,
    patterns: Optional[Dict]     = None,
    sentiment: Optional[Dict]    = None,
    narrative: str               = "",
    output_dir: str              = "data",
) -> str:
    """
    Generate a PDF analysis report and save it to output_dir.

    Args:
        symbol:      Ticker symbol (used in filename).
        quote:       Result from get_quote().
        fundamentals:Result from fundamental_analysis().
        technical:   Result from technical_analysis().
        risk:        Result from risk_score().
        patterns:    Result from pattern_detection().
        sentiment:   Result from sentiment_analysis().
        narrative:   LLM-generated plain-language summary.
        output_dir:  Directory to save the PDF (created if needed).

    Returns:
        Absolute path to the generated PDF file.
    """
    _rl()  # ensure reportlab is installed

    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import cm
    from reportlab.lib import colors
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
        HRFlowable, PageBreak,
    )

    os.makedirs(output_dir, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename  = f"analysis_{symbol.upper()}_{timestamp}.pdf"
    filepath  = os.path.join(output_dir, filename)

    PAGE_W, PAGE_H = A4
    MARGIN = 1.8 * cm
    CONTENT_W = PAGE_W - 2 * MARGIN
    generated_on = datetime.now().strftime("%d %b %Y  %H:%M")
    logo_path = _find_logo()

    doc = SimpleDocTemplate(
        filepath,
        pagesize=A4,
        leftMargin=MARGIN,
        rightMargin=MARGIN,
        topMargin=2.2 * cm,   # leave room for running header on pages 2+
        bottomMargin=1.6 * cm,
        title=f"Stock Analysis — {symbol.upper()}",
        author="Octa Bot",
        subject="Stock Market Analysis Report (Informational Only)",
        creator="Octa Bot Platform",
    )

    st = _styles()

    def rgb(t):
        return colors.Color(*t)

    story = []

    # ── COVER PAGE ──────────────────────────────────────────────────────────────
    # Full-width navy banner — clean, no separate logo column
    title_para    = Paragraph("Octa Bot  Stock Analysis Report", st["title"])
    subtitle_para = Paragraph("Powered by Octa Bot Platform  ·  Informational Use Only", st["subtitle"])

    hdr_tbl = Table(
        [[[title_para, Spacer(1, 0.18*cm), subtitle_para]]],
        colWidths=[CONTENT_W]
    )
    hdr_tbl.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), rgb(_NAVY)),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING",    (0, 0), (-1, -1), 20),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 20),
        ("LEFTPADDING",   (0, 0), (-1, -1), 16),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 16),
    ]))
    story.append(hdr_tbl)
    # Teal accent rule directly under banner
    story.append(HRFlowable(width=CONTENT_W, thickness=3, color=rgb(_TEAL),
                            spaceAfter=0.38*cm, spaceBefore=0))

    # ── Company info card ──────────────────────────────────────────────
    company_name = (
        (quote or {}).get("name")
        or (fundamentals or {}).get("name")
        or symbol.upper()
    )
    sector   = (quote or fundamentals or {}).get("sector") or (fundamentals or {}).get("sector") or "N/A"
    industry = (quote or fundamentals or {}).get("industry") or (fundamentals or {}).get("industry") or "N/A"
    currency = (quote or {}).get("currency") or (fundamentals or {}).get("currency") or "INR"

    q = quote or {}
    # ── Pre-compute all cover-page metrics ─────────────────────────────────
    price_str  = _fmt(q.get("price"),           suffix=f" {currency}", decimals=2)
    chg_str    = _signed(q.get("change_pct"))
    mktcap_str = _fmt(q.get("market_cap"),      decimals=0)
    vol_str    = _fmt(q.get("volume"),           decimals=0)
    high52_str = _fmt(q.get("52w_high"),         decimals=2)
    low52_str  = _fmt(q.get("52w_low"),          decimals=2)
    pe_str     = _fmt(q.get("pe_ratio"),         decimals=2)
    eps_str    = _fmt(q.get("eps"),              decimals=2)
    div_str    = _fmt(q.get("dividend_yield"),   suffix="%", decimals=2)
    avgvol_str = _fmt(q.get("avg_volume"),       decimals=0)
    gen_full   = datetime.now().strftime("%d %b %Y  %H:%M")

    info_data = [
        ["Symbol",    symbol.upper(),  "Exchange/Currency", currency],
        ["Company",   company_name,    "Sector",            sector],
        ["Industry",  industry,        "Generated",         gen_full],
    ]
    if q:
        info_data += [
            ["Current Price", price_str,  "Day Change",   chg_str],
            ["52W High",      high52_str, "52W Low",      low52_str],
            ["Market Cap",    mktcap_str, "Volume",       vol_str],
            ["P/E Ratio",     pe_str,     "EPS (TTM)",    eps_str],
            ["Dividend Yield",div_str,    "Avg Volume",   avgvol_str],
        ]

    info_tbl = Table(info_data, colWidths=[CONTENT_W*0.20, CONTENT_W*0.30, CONTENT_W*0.22, CONTENT_W*0.28])
    # Build per-row background commands for clean alternating rows
    _row_cmds = []
    for _ri in range(len(info_data)):
        _bg = _LIGHT if _ri % 2 == 1 else _WHITE
        _row_cmds.append(("BACKGROUND", (1, _ri), (1, _ri), rgb(_bg)))
        _row_cmds.append(("BACKGROUND", (3, _ri), (3, _ri), rgb(_bg)))
    info_tbl.setStyle(TableStyle([
        # Label columns — navy
        ("BACKGROUND",    (0, 0), (0, -1), rgb(_NAVY)),
        ("BACKGROUND",    (2, 0), (2, -1), rgb(_NAVY)),
        ("TEXTCOLOR",     (0, 0), (0, -1), colors.Color(0.72, 0.84, 0.92)),
        ("TEXTCOLOR",     (2, 0), (2, -1), colors.Color(0.72, 0.84, 0.92)),
        ("TEXTCOLOR",     (1, 0), (1, -1), rgb(_BLACK)),
        ("TEXTCOLOR",     (3, 0), (3, -1), rgb(_BLACK)),
        ("FONTNAME",      (0, 0), (-1, -1), "Helvetica"),
        ("FONTNAME",      (0, 0), (0, -1),  "Helvetica-Bold"),
        ("FONTNAME",      (2, 0), (2, -1),  "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0), (-1, -1), 8.5),
        ("LINEABOVE",     (0, 1), (-1, -1), 0.25, rgb(_DIVIDER)),
        ("LINEBEFORE",    (1, 0), (1, -1),  0.25, rgb(_DIVIDER)),
        ("LINEBEFORE",    (2, 0), (2, -1),  0.5,  rgb(_TEAL)),
        ("LINEBEFORE",    (3, 0), (3, -1),  0.25, rgb(_DIVIDER)),
        ("BOX",           (0, 0), (-1, -1), 0.5,  rgb(_LGRAY)),
        ("TOPPADDING",    (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING",   (0, 0), (-1, -1), 8),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 8),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
    ] + _row_cmds))
    story.append(info_tbl)
    story.append(Spacer(1, 0.30 * cm))

    # ── Analyst Quick Snapshot panel ───────────────────────────────────────
    from reportlab.lib.styles import ParagraphStyle as _PS  # local alias

    _tech = technical or {}
    _rsk  = risk or {}
    _fund = fundamentals or {}
    _sent = sentiment or {}

    # Technical signal
    _ts_raw = (_tech.get("signal") or _tech.get("overall_signal") or "").lower()
    if not _ts_raw:
        _trend  = (_tech.get("trend") or "").lower()
        _rsi_r  = _tech.get("rsi")
        _rsi_f  = float(_rsi_r.get("value", 50) if isinstance(_rsi_r, dict) else (_rsi_r or 50))
        if "up" in _trend or _rsi_f > 60:
            _ts_raw = "bullish"
        elif "down" in _trend or _rsi_f < 40:
            _ts_raw = "bearish"
        else:
            _ts_raw = "neutral"
    if "bull" in _ts_raw or "strong" in _ts_raw:
        _ts_label, _ts_color = "Bullish", _GREEN
    elif "bear" in _ts_raw or "sell" in _ts_raw or "weak" in _ts_raw:
        _ts_label, _ts_color = "Bearish", _RED
    else:
        _ts_label, _ts_color = "Neutral", _ORANGE

    # Risk level
    _rl_raw = (_rsk.get("risk_label") or _rsk.get("risk_level") or _rsk.get("overall_risk") or "").lower()
    _rs     = _rsk.get("risk_score")
    _rs_sfx = f"  ({_rs}/10)" if _rs is not None else ""
    if _rl_raw:
        _rl_label = _rl_raw.replace("_", " ").title() + _rs_sfx
        _rl_color = (
            _GREEN  if any(x in _rl_raw for x in ("low", "minimal"))
            else _RED    if any(x in _rl_raw for x in ("very high", "extreme", "high"))
            else _ORANGE
        )
    else:
        _rl_label, _rl_color = "N/A", _GRAY

    # Quality score
    _qs  = _fund.get("quality_score")
    _ql  = (_fund.get("quality_label") or "").title()
    if _qs is not None:
        _qstr   = f"{float(_qs):.1f}/10  {_ql}".strip()
        _qcolor = _GREEN if float(_qs) >= 7 else (_ORANGE if float(_qs) >= 5 else _RED)
    else:
        _qstr, _qcolor = "N/A", _GRAY

    # Sentiment
    _so     = (_sent.get("overall_sentiment") or "N/A")
    _ss     = _sent.get("aggregate_score")
    _so_str = _so + (f"  ({_ss:+.2f})" if _ss is not None else "")
    _so_color = _GREEN if _so == "Positive" else (_RED if _so == "Negative" else (_ORANGE if _so != "N/A" else _GRAY))

    # 52W price position
    _price_v = q.get("price")
    _h52, _l52 = q.get("52w_high"), q.get("52w_low")
    if _price_v and _h52 and _l52:
        try:
            _pp = (float(_price_v) - float(_l52)) / (float(_h52) - float(_l52)) * 100
            _pp = max(0.0, min(100.0, _pp))
            _pos_str   = f"{_pp:.0f}% of 52W range"
            _pos_color = _GREEN if _pp >= 60 else (_RED if _pp <= 30 else _ORANGE)
        except (ZeroDivisionError, TypeError, ValueError):
            _pos_str, _pos_color = "N/A", _GRAY
    else:
        _pos_str, _pos_color = "N/A", _GRAY

    # Analyst Verdict — composite score weighing technical, risk, quality,
    # sentiment, AND revenue growth (max 14 pts; BUY ≥10, HOLD ≥7, AVOID <7)
    _rv_growth = float(_fund.get("revenue_growth_yoy_pct") or 0)
    _rev_bonus = (2 if _rv_growth >= 20 else 1 if _rv_growth >= 10 else 0)  # max 2
    _ver_score = (
        (3 if _ts_label == "Bullish" else 1 if _ts_label == "Neutral" else 0)        # max 3
        + (3 if "low" in _rl_raw and "high" not in _rl_raw                             # max 3
           else 2 if any(x in _rl_raw for x in ("mod", "med", "average"))
           else 1 if _rl_raw else 0)
        + (2 if _qs is not None and float(_qs) >= 7                                    # max 2
           else 1 if _qs is not None and float(_qs) >= 5 else 0)
        + (2 if _so == "Positive" else 1 if _so == "Neutral" else 0)                  # max 2
        + _rev_bonus                                                                    # max 2
    )
    if   _ver_score >= 10: _ver_label, _ver_color = "BUY",   _GREEN
    elif _ver_score >= 7:  _ver_label, _ver_color = "HOLD",  _ORANGE
    else:                  _ver_label, _ver_color = "AVOID", _RED

    def _snap_cell(lbl_text: str, val_text: str, val_col: tuple) -> list:
        lbl = Paragraph(lbl_text.upper(), st["snap_label"])
        val = Paragraph(val_text, _PS(
            f"_sv_{lbl_text[:8]}",
            parent=st["snap_value"],
            textColor=rgb(val_col),
        ))
        return [lbl, Spacer(1, 4), val]

    _snap_col = CONTENT_W / 3
    snap_section_label = Paragraph(
        "ANALYST QUICK SNAPSHOT",
        _PS("snap_hdr", parent=st["snap_label"],
            fontSize=7, textColor=rgb(_NAVY), leading=10),
    )
    snap_grid = Table(
        [
            [_snap_cell("Technical Signal", _ts_label, _ts_color),
             _snap_cell("Risk Level",        _rl_label, _rl_color),
             _snap_cell("Quality Score",     _qstr,     _qcolor)],
            [_snap_cell("Sentiment",         _so_str,   _so_color),
             _snap_cell("52W Position",      _pos_str,  _pos_color),
             _snap_cell("Analyst Verdict",   _ver_label, _ver_color)],
        ],
        colWidths=[_snap_col, _snap_col, _snap_col],
    )
    _verdict_bg = (
        (0.95, 1.00, 0.96) if _ver_label == "BUY"
        else (1.00, 0.97, 0.92) if _ver_label == "HOLD"
        else (1.00, 0.95, 0.95)
    )
    snap_grid.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), rgb(_PANEL)),
        ("BACKGROUND",    (2, 1), (2, 1),   rgb(_verdict_bg)),
        ("BOX",           (0, 0), (-1, -1), 0.5,  rgb(_LGRAY)),
        ("INNERGRID",     (0, 0), (-1, -1), 0.25, rgb(_DIVIDER)),
        ("LINEBELOW",     (0, 0), (-1, 0),  0.75, rgb(_TEAL)),
        ("LINEBEFORE",    (2, 1), (2, 1),   1.5,  rgb(_ver_color)),
        ("VALIGN",        (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING",    (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("LEFTPADDING",   (0, 0), (-1, -1), 12),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 8),
    ]))
    story.append(snap_section_label)
    story.append(Spacer(1, 0.12 * cm))
    story.append(snap_grid)
    story.append(Spacer(1, 0.30 * cm))

    # ── Disclaimer panel ──────────────────────────────────────────────────
    disc_box = Table([[Paragraph(_DISCLAIMER, st["disc_style"])]], colWidths=[CONTENT_W])
    disc_box.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), colors.Color(0.99, 0.97, 0.90)),
        ("BOX",           (0, 0), (-1, -1), 0.5, rgb(_LGRAY)),
        ("LINEBEFORE",    (0, 0), (0, -1),  4.0, rgb(_GOLD)),
        ("TOPPADDING",    (0, 0), (-1, -1), 9),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 9),
        ("LEFTPADDING",   (0, 0), (-1, -1), 14),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 12),
    ]))
    story.append(disc_box)
    story.append(PageBreak())

    # ── SECTION 1: EXECUTIVE SUMMARY ───────────────────────────────────────────
    story.append(_section_header("1.  Executive Summary", st, CONTENT_W))
    story.append(Spacer(1, 0.25 * cm))
    if narrative:
        # Split into paragraphs for readability
        for para in narrative.split("\n"):
            para = para.strip()
            if para:
                story.append(Paragraph(para.replace("**", ""), st["body"]))
    else:
        # Auto-generate a rule-based summary from available data
        _auto = _rule_based_summary(quote, technical, fundamentals, risk, sentiment, patterns)
        if _auto:
            # Each bullet on its own line inside the panel
            _bullet_paras = [
                Paragraph(ln.strip(), st["body"])
                for ln in _auto.split("\n") if ln.strip()
            ]
            # Add small spacers between bullets
            _cell_content = []
            for i, bp in enumerate(_bullet_paras):
                _cell_content.append(bp)
                if i < len(_bullet_paras) - 1:
                    _cell_content.append(Spacer(1, 3))
            _panel = Table([[_cell_content]], colWidths=[CONTENT_W])
            _panel.setStyle(TableStyle([
                ("BACKGROUND",    (0, 0), (-1, -1), rgb(_PANEL)),
                ("BOX",           (0, 0), (-1, -1), 0.5,  rgb(_LGRAY)),
                ("LINEBEFORE",    (0, 0), (0, -1),  3.5,  rgb(_TEAL)),
                ("TOPPADDING",    (0, 0), (-1, -1), 10),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
                ("LEFTPADDING",   (0, 0), (-1, -1), 14),
                ("RIGHTPADDING",  (0, 0), (-1, -1), 12),
                ("VALIGN",        (0, 0), (-1, -1), "TOP"),
            ]))
            story.append(_panel)
        else:
            story.append(Paragraph("No narrative summary was generated.", st["body"]))
    story.append(Spacer(1, 0.3 * cm))

    # ── SECTION 2: MARKET SNAPSHOT ─────────────────────────────────────────────
    story.append(_section_header("2.  Market Snapshot", st, CONTENT_W))
    story.append(Spacer(1, 0.2 * cm))
    if quote and quote.get("status") == "success":
        q = quote
        snap_data = [
            ["Metric", "Value", "Metric", "Value"],
            ["Current Price",  _fmt(q.get("price"),         suffix=f" {q.get('currency','')}", decimals=2),
             "Volume",         _fmt(q.get("volume"),         suffix="", decimals=0, na="N/A")],
            ["Day Change",     _signed(q.get("change_pct")),
             "Avg Volume",     _fmt(q.get("avg_volume"),     suffix="", decimals=0, na="N/A")],
            ["Market Cap",     _fmt(q.get("market_cap"),     suffix="", decimals=0, na="N/A"),
             "P/E Ratio",      _fmt(q.get("pe_ratio"),       decimals=2)],
            ["52W High",       _fmt(q.get("52w_high"),       decimals=2),
             "52W Low",        _fmt(q.get("52w_low"),        decimals=2)],
            ["EPS (TTM)",      _fmt(q.get("eps"),            decimals=2),
             "Dividend Yield", _fmt(q.get("dividend_yield"), suffix="%", decimals=2)],
            ["Sector",         q.get("sector", "N/A"),
             "Industry",       q.get("industry", "N/A")],
        ]
        col_w = [CONTENT_W * 0.22, CONTENT_W * 0.28, CONTENT_W * 0.22, CONTENT_W * 0.28]
        story.append(_table(snap_data, col_w))
    else:
        # Fallback: show company info from fundamentals when real-time quote is unavailable
        _fa = fundamentals or {}
        _snap_fb = [
            ["Metric", "Value", "Metric", "Value"],
            ["Company",  _fa.get("name", symbol.upper()),   "Sector",   _fa.get("sector", "N/A")],
            ["Currency", _fa.get("currency", "N/A"),        "Industry", _fa.get("industry", "N/A")],
        ]
        story.append(_table(_snap_fb, [CONTENT_W*0.22, CONTENT_W*0.28, CONTENT_W*0.22, CONTENT_W*0.28]))
        story.append(Spacer(1, 0.15 * cm))
        story.append(Paragraph(
            "Note: Real-time price data was unavailable at report generation time.",
            st["body_small"]
        ))

    # ── SECTION 3: FUNDAMENTAL ANALYSIS ────────────────────────────────────────
    story.append(Spacer(1, 0.3 * cm))
    story.append(_section_header("3.  Fundamental Analysis  (Warren Buffett Quality Framework)", st, CONTENT_W))
    story.append(Spacer(1, 0.2 * cm))

    if fundamentals and fundamentals.get("status") == "success":
        fa = fundamentals

        # Score banner
        moat_bar   = _score_bar(fa.get("moat_score", 0),    10, fa.get("moat_label", ""))
        qual_bar   = _score_bar(fa.get("quality_score", 0), 10, fa.get("quality_label", ""))
        score_data = [
            ["Moat Score",    moat_bar],
            ["Quality Score", qual_bar],
        ]
        sc_table = Table(score_data, colWidths=[CONTENT_W * 0.25, CONTENT_W * 0.75])
        sc_table.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (0, -1), rgb(_NAVY)),
            ("TEXTCOLOR",     (0, 0), (0, -1), colors.Color(0.72, 0.84, 0.92)),
            ("FONTNAME",      (0, 0), (-1, -1), "Helvetica"),
            ("FONTNAME",      (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTSIZE",      (0, 0), (-1, -1), 8.5),
            ("LINEABOVE",     (0, 1), (-1, -1), 0.25, rgb(_DIVIDER)),
            ("LINEBEFORE",    (1, 0), (1, -1),  0.25, rgb(_DIVIDER)),
            ("BOX",           (0, 0), (-1, -1), 0.5,  rgb(_LGRAY)),
            ("TOPPADDING",    (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ("LEFTPADDING",   (0, 0), (-1, -1), 8),
            ("FONTNAME",      (1, 0), (1, -1), "Courier"),
        ]))
        story.append(sc_table)
        story.append(Spacer(1, 0.25 * cm))

        # Metrics table
        fund_data = [
            ["Quality", "Value", "Safety / Value", "Value"],
            ["Return on Equity",        _fmt(fa.get("roe_pct"),          suffix="%", decimals=1),
             "Debt / Equity",           _fmt(fa.get("debt_to_equity"),   decimals=2)],
            ["Return on Assets",        _fmt(fa.get("roa_pct"),          suffix="%", decimals=1),
             "Current Ratio",           _fmt(fa.get("current_ratio"),    decimals=2)],
            ["Gross Margin",            _fmt(fa.get("gross_margin_pct"), suffix="%", decimals=1),
             "Quick Ratio",             _fmt(fa.get("quick_ratio"),      decimals=2)],
            ["Operating Margin",        _fmt(fa.get("operating_margin_pct"), suffix="%", decimals=1),
             "P/E Ratio",               _fmt(fa.get("pe_ratio"),         decimals=2)],
            ["Net Profit Margin",       _fmt(fa.get("net_margin_pct"),   suffix="%", decimals=1),
             "Forward P/E",             _fmt(fa.get("forward_pe"),       decimals=2)],
            ["FCF Yield",               _fmt(fa.get("fcf_yield_pct"),    suffix="%", decimals=2),
             "Price / Book",            _fmt(fa.get("pb_ratio"),         decimals=2)],
            ["Earnings Growth (YoY)",   _fmt(fa.get("earnings_growth_yoy_pct"), suffix="%", decimals=1),
             "PEG Ratio",               _fmt(fa.get("peg_ratio"),        decimals=2)],
            ["Revenue Growth (YoY)",    _fmt(fa.get("revenue_growth_yoy_pct"),  suffix="%", decimals=1),
             "EV / EBITDA",             _fmt(fa.get("ev_ebitda"),        decimals=2)],
            ["Dividend Yield",          _fmt(fa.get("dividend_yield_pct"), suffix="%", decimals=2),
             "Payout Ratio",            _fmt(fa.get("payout_ratio_pct"), suffix="%", decimals=1)],
        ]
        col_w = [CONTENT_W * 0.27, CONTENT_W * 0.23, CONTENT_W * 0.27, CONTENT_W * 0.23]
        story.append(_table(fund_data, col_w))

        # Moat breakdown
        story.append(Spacer(1, 0.2 * cm))
        story.append(Paragraph("Moat Signal Breakdown:", st["bold"]))
        bdown = fa.get("moat_breakdown", {})
        for key, val in bdown.items():
            story.append(Paragraph(f"  • {key.replace('_', ' ').title()}: {val}", st["body_small"]))

    # ── SECTION 4: TECHNICAL ANALYSIS ──────────────────────────────────────────
    story.append(Spacer(1, 0.3 * cm))
    story.append(_section_header("4.  Technical Analysis", st, CONTENT_W))
    story.append(Spacer(1, 0.2 * cm))

    if technical and technical.get("status") == "success":
        tc = technical

        # Normalise RSI — may be a plain float or a sub-dict {"value":…, "signal":…}
        _rsi_raw = tc.get("rsi")
        if isinstance(_rsi_raw, dict):
            rsi_val = _rsi_raw.get("value")
            rsi_sig = (_rsi_raw.get("signal") or "").replace("_", " ").title()
        else:
            rsi_val = _rsi_raw
            if rsi_val is not None:
                rsi_sig = ("Overbought" if float(rsi_val) >= 70 else
                           "Near Overbought" if float(rsi_val) >= 65 else
                           "Near Oversold"   if float(rsi_val) <= 35 else
                           "Oversold"        if float(rsi_val) <= 30 else "Neutral")
            else:
                rsi_sig = "N/A"

        # Normalise MACD — may be plain floats or sub-dict
        _macd_raw = tc.get("macd")
        if isinstance(_macd_raw, dict):
            macd_val  = _macd_raw.get("macd")
            macd_sig  = _macd_raw.get("signal")
            macd_hist = _macd_raw.get("histogram")
            macd_text = (_macd_raw.get("signal_text") or "").title()
        else:
            macd_val  = _macd_raw
            macd_sig  = tc.get("macd_signal")
            macd_hist = (macd_val - macd_sig) if (macd_val is not None and macd_sig is not None) else None
            macd_text = "Bullish" if (macd_hist or 0) > 0 else "Bearish"

        # Normalise Bollinger — may be sub-dict or flat keys
        _bb_raw = tc.get("bollinger")
        if isinstance(_bb_raw, dict):
            bb_upper = _bb_raw.get("upper")
            bb_mid   = _bb_raw.get("middle")
            bb_lower = _bb_raw.get("lower")
            bb_sig   = (_bb_raw.get("signal") or "N/A").title()
        else:
            bb_upper = tc.get("bollinger_upper")
            bb_mid   = None
            bb_lower = tc.get("bollinger_lower")
            bb_sig   = "N/A"

        # Normalise MAs — may be sub-dict or flat keys
        _ma_raw = tc.get("moving_averages")
        if isinstance(_ma_raw, dict):
            sma20 = _ma_raw.get("sma20"); sma50 = _ma_raw.get("sma50"); sma200 = _ma_raw.get("sma200")
        else:
            sma20 = tc.get("sma_20"); sma50 = tc.get("sma_50"); sma200 = tc.get("sma_200")

        tech_data = [
            ["Indicator", "Value", "Signal", "Interpretation"],
            ["RSI (14)",
             _fmt(rsi_val, decimals=2),
             rsi_sig,
             "Overbought >70 | Near overbought 65-70 | Near oversold 30-35 | Oversold <30"],
            ["MACD",
             _fmt(macd_val, decimals=4),
             macd_text,
             f"Signal line: {_fmt(macd_sig, decimals=4)}"],
            ["MACD Histogram",
             _fmt(macd_hist, decimals=4),
             "Positive=Bullish" if (macd_hist or 0) > 0 else "Negative=Bearish",
             "Divergence from signal line"],
            ["Bollinger Upper",
             _fmt(bb_upper, decimals=2),
             bb_sig,
             f"Lower: {_fmt(bb_lower, decimals=2)}" + (f"  Mid: {_fmt(bb_mid, decimals=2)}" if bb_mid else "")],
            ["SMA 20",  _fmt(sma20,  decimals=2), "Short-term average",  "20-day simple moving average"],
            ["SMA 50",  _fmt(sma50,  decimals=2), "Medium-term average", "50-day simple moving average"],
        ]
        # Only add SMA 200 row when data is available (avoids "Price N/A SMA200" broken line)
        if sma200 is not None:
            tech_data.append([
                "SMA 200", _fmt(sma200, decimals=2), "Long-term average", "200-day simple moving average",
            ])
        col_w = [CONTENT_W * 0.19, CONTENT_W * 0.16, CONTENT_W * 0.20, CONTENT_W * 0.45]
        story.append(_table(tech_data, col_w))

    # ── SECTION 5: RISK ASSESSMENT ──────────────────────────────────────────────
    story.append(Spacer(1, 0.3 * cm))
    story.append(_section_header("5.  Risk Assessment", st, CONTENT_W))
    story.append(Spacer(1, 0.2 * cm))

    if risk and risk.get("status") == "success":
        r = risk
        risk_score_val = r.get("risk_score") or 0
        risk_level_str = r.get("risk_level") or r.get("risk_label") or r.get("overall_risk") or ""
        risk_bar = _score_bar(risk_score_val, 10, risk_level_str)

        risk_banner_data = [["Risk Score", risk_bar]]
        rb_table = Table(risk_banner_data, colWidths=[CONTENT_W * 0.20, CONTENT_W * 0.80])
        rb_table.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (0, -1), rgb(_RED if risk_score_val >= 7 else (_ORANGE if risk_score_val >= 5 else _GREEN))),
            ("TEXTCOLOR",     (0, 0), (0, -1), colors.white),
            ("FONTNAME",      (0, 0), (-1, -1), "Helvetica"),
            ("FONTNAME",      (0, 0), (0, -1),  "Helvetica-Bold"),
            ("FONTSIZE",      (0, 0), (-1, -1), 8.5),
            ("LINEBEFORE",    (1, 0), (1, -1),  0.25, rgb(_DIVIDER)),
            ("BOX",           (0, 0), (-1, -1), 0.5,  rgb(_LGRAY)),
            ("TOPPADDING",    (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ("LEFTPADDING",   (0, 0), (-1, -1), 8),
            ("FONTNAME",      (1, 0), (1, -1),  "Courier"),
        ]))
        story.append(rb_table)
        story.append(Spacer(1, 0.25 * cm))

        _bmark = r.get("benchmark", "SPY")
        # Normalise field names — support both full pipeline names and simplified names
        _vol   = r.get("annual_volatility_pct") or r.get("volatility")
        _dd    = r.get("max_drawdown_pct") or r.get("max_drawdown")
        risk_data = [
            ["Risk Metric", "Value", "Risk Metric", "Value"],
            ["Annual Volatility",      _fmt(_vol,                              suffix="%"),
             "Sharpe Ratio (1Y)",      _fmt(r.get("sharpe_ratio"),            decimals=3)],
            [f"Beta vs {_bmark} (1Y)", _fmt(r.get("beta"),                    decimals=3),
             "Sortino Ratio",          _fmt(r.get("sortino_ratio"),           decimals=3)],
            ["VaR 95% Parametric",     _fmt(r.get("var_95_daily_pct"),        suffix="%"),
             "Max Drawdown",           _fmt(_dd,                              suffix="%", decimals=2)],
            ["VaR 95% Historical",     _fmt(r.get("var_95_hist_daily_pct"),   suffix="%"),
             "Calmar Ratio",           _fmt(r.get("calmar_ratio"),            decimals=3)],
            [f"Beta 60d vs {_bmark}",  _fmt(r.get("beta_60d"),               decimals=3),
             "Annual Return",          _fmt(r.get("annual_return_pct"),       suffix="%")],
            ["Beta Downside",          _fmt(r.get("beta_downside"),           decimals=3),
             "Risk Level",             risk_level_str or "N/A"],
        ]
        col_w = [CONTENT_W * 0.27, CONTENT_W * 0.23, CONTENT_W * 0.27, CONTENT_W * 0.23]
        story.append(_table(risk_data, col_w))

        story.append(Spacer(1, 0.15 * cm))
        story.append(Paragraph(
            f"Risk Score Methodology: composite of normalised annual volatility (40%), "
            f"Beta vs {_bmark} (30%), and daily VaR 95% parametric (30%).  Score 1=low risk, 10=very high risk.  "
            f"Indian stocks (NSE/BSE) are benchmarked against NIFTY 50; US/global stocks use SPY.  "
            f"Beta Downside captures tail-risk sensitivity on negative market days.  "
            f"VaR Historical uses actual return percentiles — no normality assumption.",
            st["body_small"]
        ))

    # ── SECTION 6: PATTERN DETECTION ───────────────────────────────────────────
    story.append(Spacer(1, 0.3 * cm))
    story.append(_section_header("6.  Chart Pattern Detection", st, CONTENT_W))
    story.append(Spacer(1, 0.2 * cm))

    if patterns and patterns.get("status") == "success":
        pt = patterns
        pat_data = [
            ["Metric", "Value"],
            ["Trend",           pt.get("trend", "N/A").title()],
            ["Support Level",   _fmt(pt.get("support"),     decimals=2)],
            ["Resistance Level",_fmt(pt.get("resistance"),  decimals=2)],
            ["Latest Close",    _fmt(pt.get("latest_close"),decimals=2)],
            ["Price Position",  pt.get("price_position", "N/A").title()],
        ]
        story.append(_table(pat_data, [CONTENT_W * 0.35, CONTENT_W * 0.65]))

        story.append(Spacer(1, 0.2 * cm))
        story.append(Paragraph("Detected Candlestick Patterns:", st["bold"]))
        pat_list = pt.get("patterns") or []
        if not pat_list:
            story.append(Paragraph("  • None detected", st["body_small"]))
        else:
            for p in pat_list:
                if isinstance(p, dict):
                    _nm  = p.get("name", "Unknown")
                    _cf  = p.get("confidence", "")
                    _imp = p.get("implication", "")
                    _cf_s  = f"  [{_cf}% confidence]" if _cf else ""
                    _imp_s = f" — {_imp}" if _imp else ""
                    story.append(Paragraph(f"  • {_nm}{_cf_s}{_imp_s}", st["body"]))
                else:
                    story.append(Paragraph(f"  • {p}", st["body"]))
    else:
        story.append(Paragraph(
            "Pattern detection data unavailable or could not be processed for this symbol.",
            st["body_small"]
        ))

    # ── SECTION 7: NEWS SENTIMENT ───────────────────────────────────────────────
    story.append(Spacer(1, 0.3 * cm))
    story.append(_section_header("7.  News Sentiment Analysis", st, CONTENT_W))
    story.append(Spacer(1, 0.2 * cm))

    if sentiment and sentiment.get("status") == "success":
        sn = sentiment
        overall = sn.get("overall_sentiment", "N/A")
        sn_color = rgb(_GREEN if overall == "Positive" else (_RED if overall == "Negative" else _ORANGE))

        sn_summary = [
            ["Overall Sentiment", "Score",   "Positive", "Neutral", "Negative"],
            [overall,
             _fmt(sn.get("aggregate_score"), decimals=3),
             str(sn.get("positive_headlines", 0)),
             str(sn.get("neutral_headlines", 0)),
             str(sn.get("negative_headlines", 0))],
        ]
        sn_table = Table(sn_summary, colWidths=[
            CONTENT_W * 0.25, CONTENT_W * 0.15,
            CONTENT_W * 0.20, CONTENT_W * 0.20, CONTENT_W * 0.20,
        ])
        sn_table.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, 0), rgb(_TEAL2)),
            ("TEXTCOLOR",     (0, 0), (-1, 0), colors.white),
            ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
            ("BACKGROUND",    (0, 1), (0, 1), sn_color),
            ("FONTNAME",      (0, 0), (-1, -1), "Helvetica"),
            ("FONTNAME",      (0, 1), (0, 1), "Helvetica-Bold"),
            ("FONTSIZE",      (0, 0), (-1, -1), 8.5),
            ("LINEABOVE",     (0, 1), (-1, -1), 0.25, rgb(_DIVIDER)),
            ("LINEBEFORE",    (1, 0), (-1, -1), 0.25, rgb(_DIVIDER)),
            ("BOX",           (0, 0), (-1, -1), 0.5,  rgb(_LGRAY)),
            ("LINEBELOW",     (0, 0), (-1, 0),  1.0,  rgb(_TEAL)),
            ("TOPPADDING",    (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING",   (0, 0), (-1, -1), 8),
            ("ALIGN",         (0, 1), (0, 1), "CENTER"),
            ("TEXTCOLOR",     (0, 1), (0, 1), colors.white),
        ]))
        story.append(sn_table)

        # Engine indicator
        engine = sn.get("sentiment_engine", "keyword")
        engine_label = (
            "[OK] LLM-classified (context-aware, handles sarcasm and nuance)"
            if engine == "llm" else
            "[!] Keyword NLP fallback (LLM unavailable)"
        )
        story.append(Spacer(1, 0.1 * cm))
        story.append(Paragraph(f"Analysis engine: {engine_label}", st["body_small"]))

        # Top headlines
        story.append(Spacer(1, 0.15 * cm))
        story.append(Paragraph("Recent Headlines (sample):", st["bold"]))
        for item in (sn.get("news_items") or [])[:8]:
            label = item.get("sentiment", "Neutral")
            icon  = "[+]" if label == "Positive" else ("[-]" if label == "Negative" else "[~]")
            pub   = item.get("published", "")
            conf  = item.get("llm_confidence")
            conf_str = f" [{conf:.0%}]" if conf is not None else ""
            story.append(Paragraph(
                f"  {icon} [{pub}] {item.get('title', '')}{conf_str}  "
                f"<font color='grey'>({item.get('publisher','')})</font>",
                st["body_small"]
            ))

        story.append(Spacer(1, 0.15 * cm))
        story.append(Paragraph(
            sn.get("note", "Indicative only."),
            st["body_small"]
        ))

    # ── FOOTER DISCLAIMER ──────────────────────────────────────────────────────
    story.append(Spacer(1, 0.5 * cm))
    story.append(HRFlowable(width=CONTENT_W, thickness=0.5, color=rgb(_GRAY)))
    story.append(Spacer(1, 0.1 * cm))
    story.append(Paragraph(_DISCLAIMER, st["disc_style"]))

    # ── BUILD PDF ──────────────────────────────────────────────────────────────
    _page_cb = _make_page_cb(logo_path, symbol, generated_on, PAGE_W, PAGE_H, MARGIN)
    doc.build(story, onFirstPage=_page_cb, onLaterPages=_page_cb)
    return os.path.abspath(filepath)
